# Generated by Django 3.2.2 on 2021-05-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-weight']},
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
