# Generated by Django 3.2.2 on 2021-05-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210507_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked')], max_length=20, null=True),
        ),
    ]
